---
- hosts: 10.200.149.86
  become: yes
  vars:
    ansible_command_timeout: 300
    patch: true

  tasks:
  - name: Patching Ubuntu servers
    throttle: 5
    block:
    - name: Ubuntu - updating with apt-update
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Ubuntu - runing apt-get dist-upgrade
      apt: upgrade=dist force_apt_get=yes autoclean=yes autoremove=yes
    - name: Ubuntu - check if reboot is required
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
    - name: Ubuntu - reboot system if required
      reboot:
        msg: "Reboot initiated by Ansible due to updates"
        connect_timeout: 5
        reboot_timeout: 90
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: uptime
      when: reboot_required_file.stat.exists
    when: ansible_facts['distribution'] == 'Ubuntu' and (patch == 'true')
    become: yes
    become_user: root

  - name: Patching CentOS servers
    throttle: 5
    block:
    - name: CentOS - install yum utils
      yum:
        name: yum-utils
        state: latest
    - name: CentOS - yum update the system
      yum:
        name: "*"
        state: latest
      when: ansible_facts['distribution'] == 'CentOS' and ansible_facts ['distribution_major_version'] <= '7'
    - name: CentOS - is a reboot required
      command: "/usr/bin/needs-restarting -r"
      register: reboot_required
      ignore_errors: true
      when: ansible_facts['distribution_major_version'] == "7"
    - name: CentOS - rebooting
      reboot:
        post_reboot_delay: 60
      throttle: 1
      when: reboot_required.rc == 1
    when: ansible_facts['distribution'] == 'CentOS' and (patch == 'true')
    become: yes
    become_user: root


